name: Main

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: github-semver-parse

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn
      - name: Clean
        run: yarn clean
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  release-pull-request:
    runs-on: ubuntu-latest
    needs: [pre-commit, test]
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          command: release-pr
          package-name: ${{ env.ACTION_NAME }}
          bump-minor-pre-major: true
